---
- name: Ensure openssh-server is installed
  yum:
    name: openssh-server
    state: present

- name: Deploy sshd_config from template
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
  notify: restart sshd
